<a href="https://colab.research.google.com/github/hegdeseema20/Python_2026_learning_DE/blob/feature_branch_python_datatypes/Pandas_DataFrame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

df = pd.read_csv("/content/sample_data/california_housing_test.csv")
print(df)

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       -122.05     37.37                27.0       3885.0           661.0
1       -118.30     34.26                43.0       1510.0           310.0
2       -117.81     33.78                27.0       3589.0           507.0
3       -118.36     33.82                28.0         67.0            15.0
4       -119.67     36.33                19.0       1241.0           244.0
...         ...       ...                 ...          ...             ...
2995    -119.86     34.42                23.0       1450.0           642.0
2996    -118.14     34.06                27.0       5257.0          1082.0
2997    -119.70     36.30                10.0        956.0           201.0
2998    -117.12     34.10                40.0         96.0            14.0
2999    -119.63     34.42                42.0       1765.0           263.0

      population  households  median_income  median_house_value
0         1537.0       606.0         6.6085            344700.0
1          809.0       277.0         3.5990            176500.0
2         1484.0       495.0         5.7934            270500.0
3           49.0        11.0         6.1359            330000.0
4          850.0       237.0         2.9375             81700.0
...          ...         ...            ...                 ...
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0
2999       753.0       260.0         8.5608            500001.0

[3000 rows x 9 columns]

df.head()       --------->    # first 5 rows

df.tail()      --------->   # last 5 rows

df.columns     --------->     # column names

df.info()      --------->     # data types

df.describe()      --------->     # statistics

In [6]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [7]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [9]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           3000 non-null   float64
 1   latitude            3000 non-null   float64
 2   housing_median_age  3000 non-null   float64
 3   total_rooms         3000 non-null   float64
 4   total_bedrooms      3000 non-null   float64
 5   population          3000 non-null   float64
 6   households          3000 non-null   float64
 7   median_income       3000 non-null   float64
 8   median_house_value  3000 non-null   float64
dtypes: float64(9)
memory usage: 211.1 KB

In [11]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,3000.000000,3000.00000,3000.000000,3000.000000,3000.000000,3000.000000,3000.00000,3000.000000,3000.00000
mean,-119.589200,35.63539,28.845333,2599.578667,529.950667,1402.798667,489.91200,3.807272,205846.27500
std,1.994936,2.12967,12.555396,2155.593332,415.654368,1030.543012,365.42271,1.854512,113119.68747
min,-124.180000,32.56000,1.000000,6.000000,2.000000,5.000000,2.00000,0.499900,22500.00000
25%,-121.810000,33.93000,18.000000,1401.000000,291.000000,780.000000,273.00000,2.544000,121200.00000
50%,-118.485000,34.27000,29.000000,2106.000000,437.000000,1155.000000,409.50000,3.487150,177650.00000
75%,-118.020000,37.69000,37.000000,3129.000000,636.000000,1742.750000,597.25000,4.656475,263975.00000
max,-114.490000,41.92000,52.000000,30450.000000,5419.000000,11935.000000,4930.00000,15.000100,500001.00000

In [35]:
print(" mean value of house -",df["median_house_value"].mean())
print(" max value of house -",df["median_house_value"].max())
print(" min value of house -",df["median_house_value"].min())

 mean value of house - 205846.275
 max value of house - 500001.0
 min value of house - 22500.0

Filtering the data

In [37]:
df[df['median_house_value'] >= 500000].describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,129.000000,129.000000,129.000000,129.000000,129.000000,129.000000,129.000000,129.000000,129.000000
mean,-119.705039,35.193876,33.147287,3203.240310,564.643411,1201.465116,519.248062,7.627319,500000.968992
std,1.935068,1.766753,12.392728,2503.171347,567.399864,918.632740,513.008864,3.387378,0.174014
min,-122.490000,32.680000,5.000000,42.000000,14.000000,26.000000,14.000000,0.499900,500000.000000
25%,-122.070000,34.020000,25.000000,1790.000000,266.000000,693.000000,254.000000,4.951900,500001.000000
50%,-118.460000,34.130000,34.000000,2494.000000,435.000000,927.000000,390.000000,7.010200,500001.000000
75%,-118.340000,37.370000,42.000000,3546.000000,635.000000,1392.000000,596.000000,10.100700,500001.000000
max,-116.990000,37.870000,52.000000,18132.000000,5419.000000,7431.000000,4930.000000,15.000100,500001.000000

In [32]:
df[df['median_house_value'] <= 50000].describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000,24.000000
mean,-119.981667,36.642083,29.541667,1603.041667,396.583333,1163.416667,362.541667,1.861463,43670.833333
std,1.410207,1.657987,13.695379,1662.163584,412.351783,946.909248,361.822798,0.677369,5623.512686
min,-123.080000,32.710000,9.000000,120.000000,35.000000,140.000000,40.000000,0.825200,22500.000000
25%,-120.587500,35.867500,20.250000,905.000000,240.750000,550.500000,226.000000,1.431200,42250.000000
50%,-119.770000,36.580000,30.500000,1320.000000,317.500000,1088.000000,284.000000,1.706000,44700.000000
75%,-119.237500,37.127500,40.250000,1781.750000,443.500000,1493.000000,398.750000,2.183425,47500.000000
max,-117.160000,40.400000,52.000000,8739.000000,2190.000000,4781.000000,1919.000000,3.687500,49800.000000

In [51]:
df[(df["population"]>10000) ]["median_income"]

978     4.8811
1146    4.6357
2186    2.2612
Name: median_income, dtype: float64

Filtering by multiple conditions

In [77]:
df1=df[(df["median_house_value"]>500000) &(df["median_income"] > 10)].sort_values(by="housing_median_age")
df1["housing_median_age"].describe()

count    35.000000
mean     29.485714
std      13.697083
min       5.000000
25%      17.500000
50%      30.000000
75%      38.500000
max      52.000000
Name: housing_median_age, dtype: float64

Sorting Data

In [79]:
df.sort_values(by=["housing_median_age","median_house_value"],ascending=False).head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
128,-122.47,37.79,52.0,2844.0,623.0,1380.0,596.0,4.7500,500001.0
889,-118.36,34.06,52.0,2130.0,455.0,921.0,395.0,2.9605,500001.0
1192,-122.45,37.79,52.0,1457.0,215.0,495.0,208.0,10.7097,500001.0
1322,-118.13,34.13,52.0,2826.0,381.0,924.0,365.0,7.9976,500001.0
1510,-122.43,37.79,52.0,6186.0,1566.0,2065.0,1374.0,5.8543,500001.0

Grouping the data

In [90]:
df.groupby(by="median_income")["median_income"].count().sort_values(ascending=False)

median_income
15.0001    9
4.0000     8
3.3750     8
2.1250     7
3.2500     7
          ..
2.9200     1
2.9243     1
2.9250     1
2.9271     1
2.9135     1
Name: median_income, Length: 2578, dtype: int64

Adding new column to DataFame

In [93]:
df["new_col_test"] = df["median_income"] > 15
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'new_col_test'],
      dtype='object')

unique() -------→ list of distinct values

nunique() -------→ number of distinct values

drop_duplicates() -------→ remove duplicate rows

value_counts() -------→ frequency of each value

In [99]:
df["new_col_test"].unique()

array([False,  True])

In [100]:
df["new_col_test"].nunique()

2

In [97]:
df["new_col_test"].value_counts()

new_col_test
False    2991
True        9
Name: count, dtype: int64

In [129]:
import csv
rows = [
    {"dept": "math", "emp_id": 111, "salary": 100,"aadr" : 'Bangalore'},
    {"dept": "math", "emp_id": 111, "salary": 100,"aadr" : 'Bangalore'},
    {"dept": "math", "emp_id": 444, "salary": 150,"aadr" : 'Bangalore'},
    {"dept": "math", "emp_id": 555, "salary": 50,"aadr" : ''},
    {"dept": "science", "emp_id": 222, "salary": 200,"aadr" : 'pune'},
    {"dept": "science", "emp_id": 666, "salary": 250,"aadr" : 'pune'},
    {"dept": "AI", "emp_id": 333, "salary": 300,"aadr" : 'delhi'},
    {"dept": "AI", "emp_id": 777, "salary": 350,"aadr" : ''}
]

with open("sample_file.csv", "w", newline="") as f :
  fieldnames = ["dept", "emp_id", "salary","aadr"]
  writer = csv.DictWriter(f, fieldnames=fieldnames)
  writer.writeheader()

  writer.writerows(rows)

In [130]:
import pandas as pd
df = pd.read_csv("sample_file.csv")
print(df)

      dept  emp_id  salary       aadr
0     math     111     100  Bangalore
1     math     111     100  Bangalore
2     math     444     150  Bangalore
3     math     555      50        NaN
4  science     222     200       pune
5  science     666     250       pune
6       AI     333     300      delhi
7       AI     777     350        NaN

In [131]:
df1 = df.drop_duplicates()
print(df1)

      dept  emp_id  salary       aadr
0     math     111     100  Bangalore
2     math     444     150  Bangalore
3     math     555      50        NaN
4  science     222     200       pune
5  science     666     250       pune
6       AI     333     300      delhi
7       AI     777     350        NaN

In [139]:
df1[["dept","salary"]].groupby("dept").max()

         salary
dept
AI          350
math        150
science     250

In [140]:
df[df["salary"]  == df["salary"].max()]

  dept  emp_id  salary aadr
7   AI     777     350  NaN

Finding the if any null values and filling them with appropriate values

In [141]:
df.isnull().values.any()

np.True_

In [142]:
df.isnull().sum().sum()

np.int64(2)

In [143]:
df.isnull().sum()

dept      0
emp_id    0
salary    0
aadr      2
dtype: int64

In [146]:
df[["aadr","dept"]]

        aadr     dept
0  Bangalore     math
1  Bangalore     math
2  Bangalore     math
3        NaN     math
4       pune  science
5       pune  science
6      delhi       AI
7        NaN       AI

In [155]:
df["aadr"] = df["aadr"].fillna(df.groupby("dept")["aadr"].transform("first"))

In [156]:
df[["aadr","dept"]]

        aadr     dept
0  Bangalore     math
1  Bangalore     math
2  Bangalore     math
3  Bangalore     math
4       pune  science
5       pune  science
6      delhi       AI
7      delhi       AI

Adding new column and dropping existing column in Pandas Dataframe

In [161]:
#Adding new columns

df["bonus_m"] = df["salary"] * 0.1
df["bonus_q"] = df["salary"] * 0.5
df["new_emp_id"] = df["emp_id"] + 1000
df

      dept  emp_id  salary       aadr  bonus_m  bonus_q  new_emp_id
0     math     111     100  Bangalore     10.0     50.0        1111
1     math     111     100  Bangalore     10.0     50.0        1111
2     math     444     150  Bangalore     15.0     75.0        1444
3     math     555      50  Bangalore      5.0     25.0        1555
4  science     222     200       pune     20.0    100.0        1222
5  science     666     250       pune     25.0    125.0        1666
6       AI     333     300      delhi     30.0    150.0        1333
7       AI     777     350      delhi     35.0    175.0        1777

In [165]:
# Dropping columns
df1 = df.drop(columns="new_emp_id")
df2 = df.drop(columns=["bonus_m","bonus_q"])
#df1
#df2

      dept  emp_id  salary       aadr  new_emp_id
0     math     111     100  Bangalore        1111
1     math     111     100  Bangalore        1111
2     math     444     150  Bangalore        1444
3     math     555      50  Bangalore        1555
4  science     222     200       pune        1222
5  science     666     250       pune        1666
6       AI     333     300      delhi        1333
7       AI     777     350      delhi        1777

In [167]:
#Inplace dropping
df1.drop(columns=["bonus_m","bonus_q"],inplace=True)
df1

      dept  emp_id  salary       aadr
0     math     111     100  Bangalore
1     math     111     100  Bangalore
2     math     444     150  Bangalore
3     math     555      50  Bangalore
4  science     222     200       pune
5  science     666     250       pune
6       AI     333     300      delhi
7       AI     777     350      delhi

Adding and deleing rows in Pandas DataFrame

In [173]:
#Adding rows

new_rows = pd.DataFrame([
    ["physcics",888,75,"kolkatta"],
    ["physcics",999,100,"kolkatta"]
  ] , columns = df1.columns)

df1 = pd.concat([df1,new_rows],ignore_index=True)
df1

       dept  emp_id  salary       aadr
0      math     111     100  Bangalore
1      math     111     100  Bangalore
2      math     444     150  Bangalore
3      math     555      50  Bangalore
4   science     222     200       pune
5   science     666     250       pune
6        AI     333     300      delhi
7        AI     777     350      delhi
8  physcics     888      75   kolkatta
9  physcics     999     100   kolkatta

In [180]:
# deletting rows

df1.drop(df1[(df1["dept"] =="physcics") & (df1["salary"]== 100)].index, inplace = True)
df1

       dept  emp_id  salary       aadr
0      math     111     100  Bangalore
1      math     111     100  Bangalore
2      math     444     150  Bangalore
3      math     555      50  Bangalore
4   science     222     200       pune
5   science     666     250       pune
6        AI     333     300      delhi
7        AI     777     350      delhi
8  physcics     888      75   kolkatta

Deleting  DF

Remove DataFrame     ----->	del df

Empty DataFrame    ----- >	df = pd.DataFrame()

Remove all rows	   ----- > df = df.iloc[0:0]

In [181]:
df[1:2]

   dept  emp_id  salary       aadr  bonus_m  bonus_q  new_emp_id
1  math     111     100  Bangalore     10.0     50.0        1111

# Working with multiple DF

In [270]:
import pandas as pd

# -----------------------
# Customers DataFrame
# -----------------------
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4, 5, 6],
    "name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "city": ["Vancouver", "Toronto", "Vancouver", "Calgary", "Toronto", "Montreal"],
    "age": [25, 34, 28, 45, 22, 40]
})
print("Customers:\n", customers)

Customers:
    customer_id     name       city  age
0            1    Alice  Vancouver   25
1            2      Bob    Toronto   34
2            3  Charlie  Vancouver   28
3            4    David    Calgary   45
4            5      Eva    Toronto   22
5            6    Frank   Montreal   40

In [271]:

# -----------------------
# Products DataFrame
# -----------------------
products = pd.DataFrame({
    "product_id": [101, 102, 103, 104, 105],
    "product_name": ["Laptop", "Phone", "Tablet", "Headphones", "Monitor"],
    "category": ["Electronics", "Electronics", "Electronics", "Accessories", "Electronics"],
    "price": [1200, 800, 400, 150, 300]
})

print("\nProducts:\n", products)

Products:
    product_id product_name     category  price
0         101       Laptop  Electronics   1200
1         102        Phone  Electronics    800
2         103       Tablet  Electronics    400
3         104   Headphones  Accessories    150
4         105      Monitor  Electronics    300

In [186]:
# -----------------------
# Orders DataFrame
# -----------------------
orders = pd.DataFrame({
    "order_id": [1001, 1002, 1003, 1004, 1005, 1006, 1007],
    "customer_id": [1, 2, 1, 3, 5, 2, 7],  # NOTE: 7 does not exist in customers
    "product_id": [101, 102, 103, 104, 105, 101, 102],
    "quantity": [1, 2, 1, 3, 2, 1, 1],
    "order_date": pd.to_datetime([
        "2024-01-10", "2024-01-11", "2024-01-15",
        "2024-02-01", "2024-02-10", "2024-03-05", "2024-03-10"
    ])
})

print("\nOrders:\n", orders)

Orders:
    order_id  customer_id  product_id  quantity order_date
0      1001            1         101         1 2024-01-10
1      1002            2         102         2 2024-01-11
2      1003            1         103         1 2024-01-15
3      1004            3         104         3 2024-02-01
4      1005            5         105         2 2024-02-10
5      1006            2         101         1 2024-03-05
6      1007            7         102         1 2024-03-10

In [188]:
orders_customers = pd.merge(orders, customers, on="customer_id", how="inner")
orders_customers

,order_id,customer_id,product_id,quantity,order_date,name,city,age
0,1001,1,101,1,2024-01-10,Alice,Vancouver,25
1,1002,2,102,2,2024-01-11,Bob,Toronto,34
2,1003,1,103,1,2024-01-15,Alice,Vancouver,25
3,1004,3,104,3,2024-02-01,Charlie,Vancouver,28
4,1005,5,105,2,2024-02-10,Eva,Toronto,22
5,1006,2,101,1,2024-03-05,Bob,Toronto,34

In [189]:
orders_customers = pd.merge(orders, customers, on="customer_id", how="left")
orders_customers

,order_id,customer_id,product_id,quantity,order_date,name,city,age
0,1001,1,101,1,2024-01-10,Alice,Vancouver,25.0
1,1002,2,102,2,2024-01-11,Bob,Toronto,34.0
2,1003,1,103,1,2024-01-15,Alice,Vancouver,25.0
3,1004,3,104,3,2024-02-01,Charlie,Vancouver,28.0
4,1005,5,105,2,2024-02-10,Eva,Toronto,22.0
5,1006,2,101,1,2024-03-05,Bob,Toronto,34.0
6,1007,7,102,1,2024-03-10,NaN,NaN,NaN

In [190]:
orders_customers = pd.merge(orders, customers, on="customer_id", how="right")
orders_customers

,order_id,customer_id,product_id,quantity,order_date,name,city,age
0,1001.0,1,101.0,1.0,2024-01-10,Alice,Vancouver,25
1,1003.0,1,103.0,1.0,2024-01-15,Alice,Vancouver,25
2,1002.0,2,102.0,2.0,2024-01-11,Bob,Toronto,34
3,1006.0,2,101.0,1.0,2024-03-05,Bob,Toronto,34
4,1004.0,3,104.0,3.0,2024-02-01,Charlie,Vancouver,28
5,NaN,4,NaN,NaN,NaT,David,Calgary,45
6,1005.0,5,105.0,2.0,2024-02-10,Eva,Toronto,22
7,NaN,6,NaN,NaN,NaT,Frank,Montreal,40

In [191]:
# adding more customers

more_customers = pd.DataFrame({
    "customer_id": [7, 8],
    "name": ["Grace", "Henry"],
    "city": ["Ottawa", "Vancouver"],
    "age": [30, 27]
})

all_customers = pd.concat([customers, more_customers])
all_customers

   customer_id     name       city  age
0            1    Alice  Vancouver   25
1            2      Bob    Toronto   34
2            3  Charlie  Vancouver   28
3            4    David    Calgary   45
4            5      Eva    Toronto   22
5            6    Frank   Montreal   40
0            7    Grace     Ottawa   30
1            8    Henry  Vancouver   27

In [192]:
common_ids = set(customers["customer_id"]).intersection(set(orders["customer_id"]))
common_ids

{1, 2, 3, 5}

In [198]:
df = pd.merge(orders, products, on="product_id", how="left")
df["total_price"] = df["price"] * df["quantity"]
df

,order_id,customer_id,product_id,quantity,order_date,product_name,category,price,total_price
0,1001,1,101,1,2024-01-10,Laptop,Electronics,1200,1200
1,1002,2,102,2,2024-01-11,Phone,Electronics,800,1600
2,1003,1,103,1,2024-01-15,Tablet,Electronics,400,400
3,1004,3,104,3,2024-02-01,Headphones,Accessories,150,450
4,1005,5,105,2,2024-02-10,Monitor,Electronics,300,600
5,1006,2,101,1,2024-03-05,Laptop,Electronics,1200,1200
6,1007,7,102,1,2024-03-10,Phone,Electronics,800,800

In [230]:

customer_spending = df.groupby("customer_id")["total_price"].sum()
customer_spending_df = customer_spending.reset_index()
customer_spending_df.sort_values(by = 'total_price' , ascending=False)

#customer_spending_df = df.groupby("customer_id", as_index=False)["total_price"].sum()
# this also works directly as DataFrame

   customer_id  total_price
1            2         2800
0            1         1600
4            7          800
3            5          600
2            3          450

finding customer details who had highest total purchase

In [231]:
#as_index=False - to convert the query result into dataframe
df1 = df.groupby("customer_id", as_index=False)["total_price"].sum().sort_values(by ='total_price', ascending=False)
df1

   customer_id  total_price
1            2         2800
0            1         1600
4            7          800
3            5          600
2            3          450

In [232]:
top_customer_id = df1.nlargest(1, 'total_price')["customer_id"].iloc[0]

result = all_customers[all_customers["customer_id"] == top_customer_id]
result

   customer_id name     city  age
1            2  Bob  Toronto   34

Which city generates the most revenue?

In [237]:
df2 = df.merge(customers, on = "customer_id")
df2.columns

Index(['order_id', 'customer_id', 'product_id', 'quantity', 'order_date',
       'product_name', 'category', 'price', 'total_price', 'name', 'city',
       'age'],
      dtype='object')

In [248]:
df3 = df2.groupby("city",as_index=False)["total_price"].sum().sort_values(by = "total_price",ascending=False)
df3

        city  total_price
0    Toronto         3400
1  Vancouver         2050

In [252]:
df3.nlargest(1,"total_price")["city"].iloc[0]

'Toronto'

Most popular product (by quantity sold)

In [256]:
df4 = df.groupby("product_name",as_index=False)["quantity"].sum().sort_values(by="quantity",ascending=False)
df4

  product_name  quantity
0   Headphones         3
3        Phone         3
1       Laptop         2
2      Monitor         2
4       Tablet         1

In [257]:
df4.nlargest(1,"quantity")["product_name"].iloc[0]

'Headphones'

Average age of customers per city

In [258]:
customers.groupby("city")["age"].mean()

city
Calgary      45.0
Montreal     40.0
Toronto      28.0
Vancouver    26.5
Name: age, dtype: float64

Find invalid orders (customer_id not in customers):

In [264]:
orders[orders["customer_id"].isin(customers["customer_id"])]

   order_id  customer_id  product_id  quantity order_date
0      1001            1         101         1 2024-01-10
1      1002            2         102         2 2024-01-11
2      1003            1         103         1 2024-01-15
3      1004            3         104         3 2024-02-01
4      1005            5         105         2 2024-02-10
5      1006            2         101         1 2024-03-05

In [265]:
#negetion of the above statement!!
orders[~orders["customer_id"].isin(customers["customer_id"])]

   order_id  customer_id  product_id  quantity order_date
6      1007            7         102         1 2024-03-10

# Index, Loc, iloc

set_index()	Column → Index

reset_index()	Index → Column

In [272]:
print(customers)
# 0,1,2,3,4,5 -- > Index

   customer_id     name       city  age
0            1    Alice  Vancouver   25
1            2      Bob    Toronto   34
2            3  Charlie  Vancouver   28
3            4    David    Calgary   45
4            5      Eva    Toronto   22
5            6    Frank   Montreal   40

In [273]:
customers.set_index("customer_id", inplace=True)
customers
#Now customer_id is the index

                name       city  age
customer_id
1              Alice  Vancouver   25
2                Bob    Toronto   34
3            Charlie  Vancouver   28
4              David    Calgary   45
5                Eva    Toronto   22
6              Frank   Montreal   40

In [274]:
customers.reset_index(inplace=True)
customers
# resetiing the index

   customer_id     name       city  age
0            1    Alice  Vancouver   25
1            2      Bob    Toronto   34
2            3  Charlie  Vancouver   28
3            4    David    Calgary   45
4            5      Eva    Toronto   22
5            6    Frank   Montreal   40

In [275]:
# .iloc → Position-based (like array indexing)
# .iloc = "give me row #0, column #1"

customers.iloc[0]

customer_id            1
name               Alice
city           Vancouver
age                   25
Name: 0, dtype: object

In [276]:
customers.iloc[0:2]

   customer_id   name       city  age
0            1  Alice  Vancouver   25
1            2    Bob    Toronto   34

In [277]:
customers.iloc[0, 1]

'Alice'

In [279]:
# .loc → Label-based (uses index + column names)
customers.loc[0]

customer_id            1
name               Alice
city           Vancouver
age                   25
Name: 0, dtype: object

In [280]:
customers.loc[1, "name"]

'Bob'

axis=0 -----→ go down -----→ combine rows -----→ result per column

axis=1 -----→ go across -----→ combine columns -----→ result per row

In [281]:
print(orders)

   order_id  customer_id  product_id  quantity order_date
0      1001            1         101         1 2024-01-10
1      1002            2         102         2 2024-01-11
2      1003            1         103         1 2024-01-15
3      1004            3         104         3 2024-02-01
4      1005            5         105         2 2024-02-10
5      1006            2         101         1 2024-03-05
6      1007            7         102         1 2024-03-10

In [286]:
orders['customer_id'].mean()

np.float64(3.0)

In [290]:
orders[['customer_id','order_id']].mean(axis=1)
# for a sake of examples

0    501.0
1    502.0
2    502.0
3    503.5
4    505.0
5    504.0
6    507.0
dtype: float64